services:
  ffc-find-sfi-checker:
    build:
      context: .
      target: production
    image: ffc-find-sfi-checker
    container_name: ffc-find-sfi-checker
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-find-sfi-checker-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
