environment: production
environmentCode:
name: ffc-find-sfi-checker
namespace: ffc-find
workstream: ffc-find
image: ffc-find-sfi-checker

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-find-sfi-checker-config-map

containerSecret:
  name: ffc-find-sfi-checker-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 300Mi
  requestCpu: 300m
  limitMemory: 300Mi
  limitCpu: 300m
  port: 3000
  serviceUri: placeholder
  googleTagManagerKey: placeholder
  cookiePassword: placeholder
  indexOption: noindex, nofollow

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

ingress:
  class: nginx
  endpoint: ffc-find-sfi-checker
  server: example.com
