{{- include "ffc-helm-library.container-config-map" (list . "ffc-find-sfi-checker.config-map") -}}
{{- define "ffc-find-sfi-checker.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  SERVICE_URI: {{ quote .Values.container.serviceUri }}
  GOOGLE_TAG_MANAGER_KEY: {{ quote .Values.container.googleTagManagerKey }}
  COOKIE_PASSWORD: {{ quote .Values.container.cookiePassword }}
{{- end -}}
